#vim: set ft=ansible:
---
## The "common_packages" variable should be defiend in your env_vars.yml file
#
# common_packages:
#   - python
#   - unzip
#   - bash-completion
#   - tmux
#   - bind-utils
#   - wget
#   - ansible
#   - git
#   - vim-enhanced
######################### Install Basic Packages
- name: install basic packages
  yum:
    name: "{{ item }}"
    state: present
  with_items: "{{common_packages}}"
  tags:
    - install_common_packages
