#vim: set ft=ansible:
---
- name: Install OpenShift installer packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - atomic-openshift-clients
      - atomic-openshift-utils
      - atomic-openshift
      - httpd-tools
  tags:
   - install_openshift_provisioner_packages
